param_grids:
  - name: 'knn'
    params:
      n_neighbors: [3, 5, 7, 9]
      weights: ['uniform', 'distance']
      algorithm: ['auto', 'ball_tree', 'kd_tree', 'brute']
      leaf_size: [20, 30, 40]
      p: [1, 2]

  - name: 'rf'
    params:
      n_estimators: [100, 200, 300]
      max_features: ['auto', 'sqrt', 'log2']
      max_depth: [10, 20, 30, null]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]
      bootstrap: [true, false]

  - name: 'huber'
    params:
      epsilon: [1.1, 1.35, 1.5, 1.75, 2.0]
      alpha: [0.0001, 0.001, 0.01, 0.1, 1.0]
      max_iter: [100, 500, 1000, 1500]

  - name: 'mlp'
    params:
      hidden_layer_sizes: [(50,), (50, 25), (25, 25)]
      activation: ['relu', 'tanh']
      solver: ['adam', 'lbfgs']
      alpha: [0.0001, 0.001, 0.01]
      learning_rate: ['constant', 'invscaling', 'adaptive']

  - name: 'dt'
    params:
      max_depth: [3, 5, 7]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]

  - name: 'gb'
    params:
      n_estimators: [100, 200, 300]
      learning_rate: [0.01, 0.1, 0.2]
      max_depth: [3, 5, 7]
      subsample: [0.5, 0.75, 1.0]
      max_features: ['auto', 'sqrt', 'log2']

  - name: 'xgb'
    params:
      n_estimators: [100, 200, 300]
      learning_rate: [0.01, 0.1, 0.2]
      max_depth: [3, 5, 7]
      subsample: [0.5, 0.75, 1.0]
      colsample_bytree: [0.5, 0.75, 1.0]

  - name: 'lgbm'
    params:
      n_estimators: [100, 200, 300]
      learning_rate: [0.01, 0.1, 0.2]
      num_leaves: [10, 30, 50]
      subsample: [0.5, 0.75, 1.0]
      colsample_bytree: [0.5, 0.75, 1.0]

  - name: 'cat'
    params:
      iterations: [100, 200, 300]
      learning_rate: [0.01, 0.1, 0.2]
      depth: [3, 5, 7]
      l2_leaf_reg: [1, 3, 5]

  - name: 'svr'
    params:
      kernel: ['linear', 'poly', 'rbf']
      C: [0.1, 1.0, 10.0]
      epsilon: [0.01, 0.1, 0.5]
      gamma: ['scale', 'auto']
