column_mappings: 
  flower_stamen_colour:
    anthocyanin absent: 1
    slight anthocyanin: 2
    moderate anthocyanin: 3
    intense anthocyanin: 4

  fruit_rugosity:
    smooth: 1
    slight: 2
    moderate: 3
    intense: 4
    slight - moderate: 5
    moderate - intense: 6
    very slight: 7
    very slight - slight: 8

  fruit_hardness:
    soft: 1
    moderate: 2
    hard: 3
    very hard: 4
