# data clean_up configurations as prep for the models

db_path: "/home/public-cocoa/data/ICGD.db"

tables:
    - "flower"
    - "fruit"
    - "bean"

id_columns:
    - "Clone name"
    - "Refcode"

id_columns_new_name:
    - "clone_name"
    - "refcode"

missing_threshold: 70

target_column: "Total wet weight"

target_column_new_name: "bean_total_wet_weight"