db_path: "/home/public-cocoa/data/ICGD.db"
save_praped_data: "/home/public-cocoa/data/data_prep"
tables:
    - "flower"
    - "fruit"
    - "bean"

id_columns:
    - "Clone name"
    - "Refcode"

columns_cotyledon:
  - "bean_cotyledon_dry_weight"
  - "bean_cotyledon_length"
  - "bean_cotyledon_width"